#!/bin/bash
set -e

cp setup.cfg "$AUTOPKGTEST_TMP"

for py in $(py3versions --supported 2>/dev/null)
do
  cd "$AUTOPKGTEST_TMP"
  echo "Testing with $py:"
  http_proxy= $py -m pytest --pyargs zict
done
